stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessed.py:
    cmd: python src/data_preprocessed.py
    deps:
    - data/raw
    - src/data_preprocessed.py
    outs:
    - data/interim
  feature_eng:
    cmd: python src/feature_eng.py
    deps:
    - data/interim
    - src/feature_eng.py
    params:
    - feature_eng.max_features
    outs:
    - data/processed
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    params:
    - model_training.n_estimators
    - model_training.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
#     metrics:
#     - reports/metrics.json
# params:
# - dvclive/params.yaml
# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
